# Generated by Django 5.2.10 on 2026-02-18 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Device brand (e.g. Apple, Samsung)', max_length=100)),
                ('model', models.CharField(help_text='Device model (e.g. iPhone 13, Galaxy S22)', max_length=100)),
                ('serial_number', models.CharField(blank=True, help_text='Serial number / IMEI (optional)', max_length=100)),
                ('condition_description', models.TextField(help_text="Customer's description of the device's current condition")),
                ('submission_date', models.DateTimeField(auto_now_add=True, help_text='When the submission was created')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review')], default='PENDING', help_text='Current status of the submission', max_length=20)),
                ('video', models.FileField(blank=True, help_text='Optional short video showing device functionality', null=True, upload_to='submission_videos/')),
                ('customer', models.ForeignKey(help_text='The customer who submitted the device', on_delete=django.db.models.deletion.CASCADE, related_name='device_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Submission',
                'verbose_name_plural': 'Device Submissions',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photo of the device (multiple angles recommended)', upload_to='submission_photos/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the photo was uploaded')),
                ('submission', models.ForeignKey(help_text='The submission this photo belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='submissions.devicesubmission')),
            ],
            options={
                'verbose_name': 'Submission Photo',
                'verbose_name_plural': 'Submission Photos',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
