# Generated by Django 5.2.10 on 2026-05-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesubmission',
            name='certificate_id',
            field=models.CharField(blank=True, help_text='Unique certificate ID if device is certified', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devicesubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review'), ('CERTIFIED', 'Certified'), ('REFURBISH', 'Refurbishment')], default='PENDING', help_text='Current status of the submission', max_length=20),
        ),
    ]
