# Generated by Django 5.2.10 on 2026-05-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_devicesubmission_certificate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesubmission',
            name='category',
            field=models.CharField(blank=True, help_text='Device category (Smartphone, Laptop, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devicesubmission',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated resale price after certification', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='devicesubmission',
            name='final_notes',
            field=models.TextField(blank=True, help_text='Final certification notes by staff', null=True),
        ),
        migrations.AlterField(
            model_name='devicesubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review'), ('CERTIFIED', 'Certified'), ('REFURBISH', 'Refurbishment'), ('READY_FOR_SALE', 'Ready for Sale')], default='PENDING', help_text='Current status of the submission', max_length=20),
        ),
    ]
