# Generated by Django 5.2.10 on 2026-05-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_devicesubmission_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review'), ('CERTIFIED', 'Certified'), ('REFURBISH', 'Refurbishment'), ('PUBLISHED', 'Published to Catalog')], default='PENDING', help_text='Current status of the submission', max_length=20),
        ),
    ]
