# Generated by Django 5.2.10 on 2026-06-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_alter_devicesubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesubmission',
            name='diagnostic_notes',
            field=models.TextField(blank=True, help_text='Staff diagnostic notes during testing', null=True),
        ),
        migrations.AddField(
            model_name='devicesubmission',
            name='diagnostic_results',
            field=models.JSONField(blank=True, help_text='Stores diagnostic checklist results (Pass/Fail data)', null=True),
        ),
    ]
