# Generated by GitHub Copilot - reservation model migration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_devicesubmission_diagnostic_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, help_text='When the reservation was created')),
                ('customer', models.ForeignKey(on_delete=models.CASCADE, related_name='reservations', to='users.user', help_text='The customer who reserved the device')),
                ('device_submission', models.OneToOneField(help_text='The published device that has been reserved', on_delete=models.CASCADE, related_name='reservation', to='submissions.devicesubmission')),
            ],
            options={
                'ordering': ['-reserved_at'],
                'verbose_name': 'Device Reservation',
                'verbose_name_plural': 'Device Reservations',
            },
        ),
    ]
