# Generated by GitHub Copilot - add status field to reservation model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_create_reservation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicereservation',
            name='status',
            field=models.CharField(
                choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')],
                default='ACTIVE',
                help_text='Reservation status',
                max_length=20,
            ),
        ),
    ]
